name: Run Golang
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Use Go 1.15
      uses: cedrickring/golang-action/go1.15@1.6.0
    - name: Run pcu.go
      run: |
        go run cmd/pcu.go -f=requirements_test.txt